[package]
name = "lit-poly"
version = "0.1.0"
edition = "2021"

[dependencies]
elliptic-curve = { version = "0.13", features = ["arithmetic"] }
hex = "0.4"
rand = "0.8"
rayon = "1.8"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
k256 = "0.13"
rand_chacha = "0.3"
