[package]
name = "lit-poly"
version = "0.1.0"
edition = "2021"

[dependencies]
elliptic-curve = { version = "0.13", features = ["arithmetic"] }
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
